version: '2.16'

services:
  posgresql:
    image: postgres:latest # Образ, который мы будем использовать
    container_name: my-netology-db # Имя, которым будет называться наш контейнер
    ports: # Порты, которые мы пробрасываем с нашего докер сервера внутрь контейнера
      - 5432:5432
    volumes: # Папка, которую мы пробросим с докер сервера внутрь контейнера
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment: # Переменные среды
      POSTGRES_PASSWORD: MySuppeRpa$$word # Задаём пароль от пользователя postgres
      POSTGRES_DB: my-db # БД которая сразу же будет создана
      PGDATA: /var/lib/postgresql/data/pgdata # Путь внутри контейнера, где будет папка pgdata
    networks:
      my-netology-hw:
        ipv4_address: 172.22.0.2
    restart: always # Режим перезапуска контейнера. Контейнер всегда будет перезапускаться

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: my@ilove-netology.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "61231:80"
    networks:
      my-netology-hw:
        ipv4_address: 172.22.0.3
    restart: always

  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    links:
      - posgresql
    container_name: my-zabbix-netology
    environment:
      DB_SERVER_HOST: '172.22.0.2'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MySuppeRpa$$word
    ports:
      - "10051:10051"
    networks:
      my-netology-hw:
        ipv4_address: 172.22.0.4
    restart: always

  zabbix_frontend:
    image: zabbix/zabbix-web-apache-pgsql
    links:
      - posgresql
      - zabbix-server
    container_name: my-netology-zabbix-frontend
    environment:
      DB_SERVER_HOST: '172.22.0.2'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: MySuppeRpa$$word
      ZBX_SERVER_HOST: "zabbix_wgui"
      PHP_TZ: "Europe/Moscow"
    ports:
      - "80:8080"
      - "443:8443"
    networks:
      my-netology-hw:
        ipv4_address: 172.22.0.5
    restart: always

networks:
  my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24
  
